language: shell

env:
  global:
    - NAME='zorel'
    - DEVICE_TREE_URL='https://github.com/ZorEl212/android_device_xiaomi_ginkgo.git'
    - DEVICE_TREE_BRANCH='android-12.1'
    - DEVICE_PATH='device/xiaomi/ginkgo'
    - DEVICE_NAME='ginkgo'
    - MAKEFILE_NAME='twrp_ginkgo'
    - BUILD_TARGET='recovery'

jobs:
  include:
    - name: Build
      os: linux
      dist: bionic
      script:
        - sudo apt update
        - sudo apt -y upgrade
        - bash install_dependencies.sh  # Create a script for installing dependencies
        - mkdir ~/bin
        - curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        - chmod a+x ~/bin/repo
        - export PATH=~/bin:$PATH
        - mkdir workspace
        - cd workspace
        - git config --global user.name "ZorEl212"
        - git config --global user.email"yabsirad212@proton.me"

        - echo -e "y\n" | repo init --depth=1 -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-12.1
        - repo sync -j$(nproc --all) -f --force-sync
        - ls -al
        - git clone https://github.com/ZorEl212/twrp_xiaomi_ginkgo.git  -b android-12.1 device/xiaomi/ginkgo
        - PATH=~/bin:$PATH
        - source build/envsetup.sh
        - repopick 5405 5540
        - lunch twrp_ginkgo-eng
        - export ALLOW_MISSING_DEPENDENCIES=true
        - make clean
        -  make $BUILD_TARGET -j$(nproc --all)
